[package]
name = "axm_cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "axm_cli"
path = "src/lib.rs"

[[bin]]
name = "axm"
path = "src/main.rs"

[dependencies]


clap = { version =  '4.5', features = ['derive'] } 

